name: ActionTest
on: 
  workflow_dispatch:
jobs:
  pre:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set AVERSION
      run: echo "AVERSION=$(docker run --rm alpine:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=')" >> $GITHUB_ENV
    - name: Test AVERSION
      run: echo $AVERSION
