name: ActionTest-3
on: 
  workflow_dispatch:
jobs:

  SetVariables:
    runs-on: self-hosted
    steps:
      - name: SetVariables
        run: |
          echo "AVERSION=$(docker run --rm alpine:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=')" >> $GITHUB_ENV
          echo "UVERSION=$(docker run --rm ubuntu:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=' | cut -f2 -d"\"")" >> $GITHUB_ENV

  BuildImages:
    runs-on: self-hosted
    steps:
      - name: BuildImages
        run: |
          echo "Building Alpine Base: v${AVERSION}"
          docker build --force-rm --rm --tag ghcr.io/agpsn/alpine-base:latest --tag ghcr.io/agpsn/alpine-base:$AVERSION -f ./Dockerfile.alpine .
          echo "Building Ubuntu Base: v${UVERSION}"
          docker build --force-rm --rm --tag ghcr.io/agpsn/ubuntu-base:latest --tag ghcr.io/agpsn/ubuntu-base:$UVERSION -f ./Dockerfile.ubuntu .

  PushImages:
    runs-on: self-hosted
    steps:
      - name: PushImages
        run: |
          echo "Pushing Alpine Base: v${AVERSION}"
          docker push ghcr.io/agpsn/alpine-base:latest
          docker push ghcr.io/agpsn/alpine-base:$AVERSION
          echo "Pushing Ubuntu Base: v${UVERSION}"
          docker push ghcr.io/agpsn/ubuntu-base:latest
          docker push ghcr.io/agpsn/ubuntu-base:$UVERSION
          
  GithubTags:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "{AVERSION}"
          tag_exists_error: false
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "{UVERSION}"
          tag_exists_error: false
#      - name: Github Tags (Alpine)
#        with:
#          tag: "${AVERSION}"
#          tag_exists_error: false
#      - name: Github Tags (Ubuntu)
#        with:
#          tag: "${AVERSION}"
#          tag_exists_error: false
#         run: | 
#           git tag -f $AVERSION && git push origin $AVERSION -f --tags
#           git tag -f $UVERSION && git push origin $UVERSION -f --tags
#       - name: Commit Changes
#         run: |
#           git add . && git commit -am "Updated" && git push --quiet
