name: ActionTest-6
on: 
  workflow_dispatch:

jobs:
  TESTING:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: SetVariables
        run: |
          echo "AVERSION=$(docker run --rm alpine:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=')" >> $GITHUB_ENV
          echo "UVERSION=$(docker run --rm ubuntu:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=' | cut -f2 -d"\"")" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: 'v1.13.1'
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/agpsn/alpine-base:latest
            ghcr.io/agpsn/alpine-base:$AVERSION
            ghcr.io/agpsn/ubuntu-base:latest
            ghcr.io/agpsn/ubuntu-base:$UVERSION
      - name: BuildImages
        run: |
          echo "Building Alpine Base: v${AVERSION}"
          docker build --force-rm --rm --tag ghcr.io/agpsn/alpine-base:latest --tag ghcr.io/agpsn/alpine-base:$AVERSION -f ./Dockerfile.alpine .
          echo "Building Ubuntu Base: v${UVERSION}"
          docker build --force-rm --rm --tag ghcr.io/agpsn/ubuntu-base:latest --tag ghcr.io/agpsn/ubuntu-base:$UVERSION -f ./Dockerfile.ubuntu .

  PushImages:
    runs-on: self-hosted
    steps:
      - name: PushImages
        run: |
          echo "Pushing Alpine Base: v${AVERSION}"
          docker push ghcr.io/agpsn/alpine-base:latest
          docker push ghcr.io/agpsn/alpine-base:$AVERSION
          echo "Pushing Ubuntu Base: v${UVERSION}"
          docker push ghcr.io/agpsn/ubuntu-base:latest
          docker push ghcr.io/agpsn/ubuntu-base:$UVERSION
          
  GithubTags:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "{AVERSION}"
          tag_exists_error: false
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "{UVERSION}"
          tag_exists_error: false
#      - name: Github Tags (Alpine)
#        with:
#          tag: "${AVERSION}"
#          tag_exists_error: false
#      - name: Github Tags (Ubuntu)
#        with:
#          tag: "${AVERSION}"
#          tag_exists_error: false
#         run: | 
#           git tag -f $AVERSION && git push origin $AVERSION -f --tags
#           git tag -f $UVERSION && git push origin $UVERSION -f --tags
#       - name: Commit Changes
#         run: |
#           git add . && git commit -am "Updated" && git push --quiet
