name: ActionTest
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set AVERSION
#      run: echo "AVERSION=$(docker run --rm alpine:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=')" >> $GITHUB_ENV
#    - name: Set UVERSION
#      run: echo "UVERSION=$(docker run --rm ubuntu:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=' | cut -f2 -d"\"")" >> $GITHUB_ENV
#    - name: Test AVERSION
#      run: echo $AVERSION
#    - name: Test UVERSION
#      run: echo $UVERSION

    steps:
      - uses: actions/checkout@v3
      - name: Set Variables
        run: |
          echo "AVERSION=$(docker run --rm alpine:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=')" >> $GITHUB_ENV
          echo "UVERSION=$(docker run --rm ubuntu:latest cat /etc/os-release | grep VERSION_ID | cut -f2 -d'=' | cut -f2 -d"\"")" >> $GITHUB_ENV
      - name: Test Results
        run: |
          echo "${AVERSION}"
          echo "${UVERSION}"
