name: ActionTest-11
on: 
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io

jobs:
  Testing3:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        id: step1
        uses: actions/checkout@v3

#      - name: Install cosign
#        id: step2
#        if: github.event_name != 'pull_request'
#        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
#        with:
#          cosign-release: 'v1.13.1'
#
#      - name: Setup Docker buildx
#        id: step3
#        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
#
#      - name: Log into registry ${{ env.REGISTRY }}
#        id: step4
#        if: github.event_name != 'pull_request'
#        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
#        with:
#          registry: ${{ env.REGISTRY }}
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#
#      - name: Extract Docker metadata
#        id: step5a
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: |
#            ghcr.io/agpsn/alpine-base:latest
#            ghcr.io/agpsn/alpine-base:$AVERSION
#            
#      - name: Extract Docker metadata
#        id: step5b
#        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#        with:
#          images: |
#            ghcr.io/agpsn/ubuntu-base:latest
#            ghcr.io/agpsn/ubuntu-base:$UVERSION
#
#      - name: Build and push
#        id: step6a
#        uses: docker/build-push-action@v4
#        with:
#          context: ./Dockerfile.alpine
##          labels: ${{ steps.meta.outputs.labels }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: |
#            ghcr.io/agpsn/alpine-base:latest
#            ghcr.io/agpsn/alpine-base:$AVERSION
#            
#      - name: Build and push
#        id: step6b
#        uses: docker/build-push-action@v4
#        with:
#          context: ./Dockerfile.ubuntu
##          labels: ${{ steps.meta.outputs.labels }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          push: ${{ github.event_name != 'pull_request' }}
#          tags: |
#            ghcr.io/agpsn/ubuntu-base:latest
#            ghcr.io/agpsn/ubuntu-base:$UVERSION
#
##      - name: Sign the published Docker image
##        id: step7
##        if: ${{ github.event_name != 'pull_request' }}
##        env:
##          COSIGN_EXPERIMENTAL: "true"
##        run: |
##          echo "${{ steps.step5a.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.step6a.outputs.digest }}
##          echo "${{ steps.step5b.outputs.tags }}" | xargs -I {} cosign sign {}@${{ steps.step6b.outputs.digest }}
